# Generated by Django 3.1 on 2020-12-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201213_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('TOYS', 'Toys'), ('SPORTING_GOODS', 'Sporting Goods'), ('BABY_PRODUCTS', 'Baby Products'), ('OTHER', 'Other')], default='HOME_&_OFFICE', max_length=20),
        ),
    ]
