# Generated by Django 3.1 on 2020-12-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201213_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion'), ('HOME_&_OFFICE', 'Home & Office'), ('TOYS', 'Toys'), ('SPORTING_GOODS', 'Sporting Goods'), ('BABY_PRODUCTS', 'Baby Products'), ('OTHER', 'Other')], default='ELECTRONICS', max_length=20),
        ),
    ]
